//------------------------------------------------------------------------------
/// <autogenerated>
///     This code was generated by a tool.
///     Runtime Version: 1.1.4322.573
///
///     Changes to this file may cause incorrect behavior and will be lost if 
///     the code is regenerated.
/// </autogenerated>
//------------------------------------------------------------------------------

//@cc_on
//@set @debug(off)


package MyNameSpace
{
    
    public class MyClass
    {
        
        public function MonMethod()
        {
            if (boolVar)
            {
                //If Outer If condition is true execute these statements
                if (otherBoolVar)
                {
                    //If the Inner If is true execute these statements
                }
                else
                {
                    //If the Inner If is false execute these statements
                }
                //Continue with Other statements in the Outer If
            }
            else
            {
                //Outer Else block. If condition is false, execute these statements.
            }
        }
    }
}
