//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace MyNameSpace
{
    
    
    public class MyClass
    {
        
        public virtual void MonMethod()
        {
            try
            {
                this.ThrowApplicationException();
            }
            catch (System.ApplicationException ex)
            {
                // Handle any SystemApplicationException here
            }
            catch (System.Exception ex)
            {
                // Handle any other exception type here
            }
            finally
            {
                // Handle any finally block statements
            }
        }
    }
}
