//------------------------------------------------------------------------------
/// <autogenerated>
///     This code was generated by a tool.
///     Runtime Version: 1.1.4322.573
///
///     Changes to this file may cause incorrect behavior and will be lost if 
///     the code is regenerated.
/// </autogenerated>
//------------------------------------------------------------------------------

//@cc_on
//@set @debug(off)


package MyNameSpace
{
    
    public class MyClass
    {
        
        public function MonMethod()
        {
            try
            {
                this.ThrowApplicationException();
            }
            catch (ex : System.ApplicationException)
            {
                //Handle any SystemApplicationException here
            }
            catch (ex : System.CriticalException)
            {
                //Handle any other exception type here
            }
            finally
            {
                //Handle any finally block statements
            }
        }
    }
}
