//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace MyNameSpace
{
    
    
    public class MyClass
    {
        
        public virtual void MyMethod()
        {
            SomeVar = "TestString";
            SomeVar = 10;
            SomeVar = 10.2;
            SomeVar = null;
        }
    }
}
