'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace MyNameSpace
    
    Public Class Type1
        
        Public Overridable Sub MonMethod()
            goto JumpToLabel
            System.Console.WriteLine("Test Output")
        JumpToLabel:
            System.Console.WriteLine("Output from Labeled statement")
        End Sub
    End Class
End Namespace
