//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace MyNameSpace
{
    
    
    public class MyClass
    {
        
        public virtual void MonMethod()
        {
            int testInt = 0;
            for (testInt = 1; (testInt < 10); (testInt + 1))
            {
                // for statements come here
                System.Console.WriteLine(testInt.ToString());
            }
        }
    }
}
