'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace MyNameSpace
    
    Public Class [MyClass]
        
        Public Overridable Sub MonMethod()
            If boolVar Then
                'If Outer If condition is true execute these statements
                If otherBoolVar Then
                    'If the Inner If is true execute these statements
                Else
                    'If the Inner If is false execute these statements
                End If
                'Continue with Other statements in the Outer If
            Else
                'Outer Else block. If condition is false, execute these statements.
            End If
        End Sub
    End Class
End Namespace
