'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace MyNameSpace
    
    Public Class BaseType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TestStringParameter As String)
            MyBase.New
        End Sub
    End Class
    
    Public Class DerivedType
        Inherits BaseType
        
        Public Sub New(ByVal System.CodeDom.CodeArgumentReferenceExpression As String)
            MyBase.New(TestStringParameter)
        End Sub
        
        Public Sub New()
            MyBase.New("test")
        End Sub
        
        Public Sub New(ByVal TestIntParameter As Integer)
            Me.New()
        End Sub
    End Class
End Namespace
