//------------------------------------------------------------------------------
/// <autogenerated>
///     This code was generated by a tool.
///     Runtime Version: 1.1.4322.573
///
///     Changes to this file may cause incorrect behavior and will be lost if 
///     the code is regenerated.
/// </autogenerated>
//------------------------------------------------------------------------------

//@cc_on
//@set @debug(off)


package MyNameSpace
{
    
    public class Type1
    {
        
        private var integerField : int;
        
        public function Type1()
        {
            
        }
        
        public function get integerProperty() : int
        {
            return this.integerField;
        }
        public function set integerProperty(value : int)
        {
            this.integerField = value;
        }
    }
}
