'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace MyNameSpace
    
    Public Class TestType
        Inherits BaseType
    End Class
    
    Public NotInheritable Class TestdType2
        Inherits BaseType
        Implements BaseType2
    End Class
    
    Public Interface aa
        Inherits bb
    End Interface
End Namespace
