//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6400
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNameSpace
{
    
    
    public class MyClass
    {
        
        public virtual void WriteString(string text)
        {
            Console.WriteLine(text);
        }
    }
}
