'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace MyNameSpace
    
    Public Class Type1
        
        Private integerField As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Overridable Property integerProperty As Integer
            Get
                Return Me.integerField
            End Get
            Set
                Me.integerField = value
            End Set
        End Property
    End Class
End Namespace
