'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace MyNameSpace
    
    Public Class [MyClass]
        
        Public Overridable Sub MonMethod()
            Dim testInt As Integer = 0
            testInt = 1
            Do While (testInt < 10)
                'for statements come here
                System.Console.WriteLine(testInt.ToString)
                (testInt + 1)
            Loop
        End Sub
    End Class
End Namespace
