//------------------------------------------------------------------------------
/// <autogenerated>
///     This code was generated by a tool.
///     Runtime Version: 1.1.4322.573
///
///     Changes to this file may cause incorrect behavior and will be lost if 
///     the code is regenerated.
/// </autogenerated>
//------------------------------------------------------------------------------

//@cc_on
//@set @debug(off)


package MyNameSpace
{
    
    public class MyClass
    {
        
        public function get StringProperty() : System.String
        {
            //Get Statements come here
            return this.testStringField;
        }
        public function set StringProperty(value : System.String)
        {
            //Set statements come here
            this.testStringField = value;
        }
    }
}
