//------------------------------------------------------------------------------
/// <autogenerated>
///     This code was generated by a tool.
///     Runtime Version: 2.0.50727.6400
///
///     Changes to this file may cause incorrect behavior and will be lost if 
///     the code is regenerated.
/// </autogenerated>
//------------------------------------------------------------------------------

//@cc_on
//@set @debug(off)


package MyNameSpace
{
    
    public class MyClass
    {
        
        public function WriteString(text : System.String)
        {
            Console.WriteLine(text);
        }
    }
}
