'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System

Namespace MyNameSpace
    
    Public Class Class1
        
        Public Overridable Sub ClassMethod()
            Me.ThisMethod(Me.TestParameter)
        End Sub
    End Class
End Namespace
