//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace MyNameSpace
{
    
    
    public class BaseType
    {
        
        public BaseType()
        {
        }
        
        public BaseType(string TestStringParameter)
        {
        }
    }
    
    public class DerivedType : BaseType
    {
        
        public DerivedType(string TestStringParameter) : 
                base(TestStringParameter)
        {
        }
        
        public DerivedType() : 
                base("test")
        {
        }
        
        public DerivedType(int TestIntParameter) : 
                this()
        {
        }
    }
}
