'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace MyNameSpace
    
    Public Class [MyClass]
        
        Public Overridable Sub MonMethod()
            RemoveHandler TestEvent, AddressOf Me.TestMethod
            RemoveHandler TestEvent2, AddressOf Me.TestMethod
            RemoveHandler TestEvent, AddressOf Me.TestMethod2
            RemoveHandler TestEvent3, AddressOf Me.TestMethod3
        End Sub
    End Class
End Namespace
