//------------------------------------------------------------------------------
/// <autogenerated>
///     This code was generated by a tool.
///     Runtime Version: 1.1.4322.573
///
///     Changes to this file may cause incorrect behavior and will be lost if 
///     the code is regenerated.
/// </autogenerated>
//------------------------------------------------------------------------------

//@cc_on
//@set @debug(off)

import System;

package MyNameSpace
{
    
    public class Class1
    {
        
        public static function Main()
        {
            System.Console.WriteLine("Hello World from Mr. ZADCO");
        }
    }
}
MyNameSpace.Class1.Main();
