'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace MyNameSpace
    
    Public Class [MyClass]
        
        Public Overridable Property StringProperty As String
            Get
                'Get Statements come here
                Return Me.testStringField
            End Get
            Set
                'Set statements come here
                Me.testStringField = value
            End Set
        End Property
    End Class
End Namespace
